### ISSUE TITLE
Support album cover color palette data

### ISSUE THREAD

**Issue by VelocityRa** [dbeley/rymscraper#32]
Contains the color palette of album art.
Probably uses an algorithm similar to [Color Thief](https://lokeshdhakar.com/projects/color-thief/) in the backend.

#### Screenshot
![image](https://user-images.githubusercontent.com/6632271/122137066-7b83be80-ce4c-11eb-8380-aae1ab73fe15.png)

#### HTML
![image](https://user-images.githubusercontent.com/6632271/122137318-0664b900-ce4d-11eb-927e-ed0e7c61b199.png)

**Comment by dbeley** [comment]
Hello, thanks for the input it has been added with https://github.com/dbeley/rymscraper/commit/d52c1c157883374f93a98b6d67b68718ea8ac4ba in the `Colorscheme` attribute of an album!
